apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      serviceAccountName: secret-manager-service-account
      containers:
      - name: {{ .Values.container.name }}
        command: [ "npm", "run", "start:dev" ]
        image:  {{ printf "%s:%s" .Values.image.repo .Values.image.tag | quote }}
        ports:
        - containerPort: {{ .Values.container.port }}
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: static-files
          mountPath: /app/public
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.metadata.name }}
              key: NODE_ENV
        - name: CONTENTFUL_DELIVERY_API_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.metadata.name }}
              key: CONTENTFUL_DELIVERY_API_HOST
        - name: CONTENTFUL_PREVIEW_API_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.metadata.name }}
              key: CONTENTFUL_PREVIEW_API_HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.metadata.name }}
              key: PORT
        - name: CONTENTFUL_SPACE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.Secret.metadata.name }}
              key: CONTENTFUL_SPACE_ID
        - name: CONTENTFUL_DELIVERY_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.Secret.metadata.name }}
              key: CONTENTFUL_DELIVERY_TOKEN
        - name: CONTENTFUL_PREVIEW_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.Secret.metadata.name }}
              key: CONTENTFUL_PREVIEW_TOKEN
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "600m"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "secrets-provider"
      - name: static-files
        hostPath:
          path: /home/ec2-user/volume
          type: DirectoryOrCreate