apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.pod.metadata.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
