apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: {{ .Values.configMap.clusterName }}
  http.port: "2020"
  http.server: "On"
  logs.region: {{ .Values.configMap.region }}
  read.head: "Off"
  read.tail: "On"