apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountsRoles.secretManagerArn }}