---
  - name: Build and push to ECR
    hosts: localhost
    become: yes
    tasks:
      - name: Login into ECR
        ansible.builtin.shell: |
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 056201179630.dkr.ecr.us-east-1.amazonaws.com
      - name: Generate image tag
        set_fact:
          image_tag: "{{ lookup('community.general.random_string', length=15) | hash('md5') }}" 
      - name: Create temporary repo folder
        file:
          path: /tmp/nodejs_app
          state: directory
      - name: Clone git repo
        ansible.builtin.git:
          repo: 'https://github.com/pibblokto/its-testtask-node.git'
          dest: /tmp/nodejs_app
      - name: install npm modules
        ansible.builtin.shell: |
          cd /tmp/nodejs_app/app
          npm install
      - name: Build an image and push it to a private repo
        docker_image:
          build:
            path: /tmp/nodejs_app/app
          name: 056201179630.dkr.ecr.us-east-1.amazonaws.com/nodejs_app
          tag: "{{ image_tag }}"
          push: true
          source: build
      - name: Add tag latest to image
        docker_image:
          name: 056201179630.dkr.ecr.us-east-1.amazonaws.com/nodejs_app:{{ image_tag }}
          repository: 056201179630.dkr.ecr.us-east-1.amazonaws.com/nodejs_app:latest
          # As 'latest' usually already is present, we need to enable overwriting of existing tags:
          force_tag: true
          source: local
      - name: Push latest to repo
        docker_image:
          name: 056201179630.dkr.ecr.us-east-1.amazonaws.com/nodejs_app:latest
          push: true
          source: local
      - name: Remove repo
        ansible.builtin.file:
          path: /tmp/nodejs_app
          state: absent
      #- name: Remove all images generated during build
      #  shell: "for i in $(sudo docker image ls -q); do sudo docker image rm -f $i; done"